-- Update image_url for all 129 seeded meals using Cloudinary URLs
-- Generated from cloudinary_assets.md (naija-eats/ folder)

UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/jollof_rice.jpg' WHERE name = 'Jollof Rice';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fried_rice.jpg' WHERE name = 'Fried Rice';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/moi_moi.jpg' WHERE name = 'Moi Moi';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/pepper_soup.jpg' WHERE name = 'Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/ewagonyi.jpg' WHERE name = 'Ewa Agoyin';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/ofada_rice.jpg' WHERE name = 'Ofada Rice';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/yam_porrigde.jpg' WHERE name = 'Yam Porridge';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/african_fish_stew.jpg' WHERE name = 'Fish Stew';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/chicken_stew.jpg' WHERE name = 'Chicken Stew';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/beef_soup.jpg' WHERE name = 'Beef Stew';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/edikang_ikong_soup.jpg' WHERE name = 'Edikang Ikong';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/ukodo.jpg' WHERE name = 'Ukodo';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/gbegiri.jpg' WHERE name = 'Gbegiri';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/danwake.jpg' WHERE name = 'Dan Wake';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/ayamase.jpg' WHERE name = 'Ayamase';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/karkashi_soup.jpg' WHERE name = 'Karkashi Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/editan_soup_eba.jpg' WHERE name = 'Editan Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/coconut_rice.jpg' WHERE name = 'Coconut Rice';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/beans_plantain.jpg' WHERE name = 'Beans and Plantain';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/porridge_beans.jpg' WHERE name = 'Porridge Beans';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/spaghetti.jpg' WHERE name = 'Spaghetti Jollof';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/catfish.jpg' WHERE name = 'Grilled Catfish';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/cowleg_pepper_soup.jpg' WHERE name = 'Cowleg Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/goat_meat_pepper_soup.jpg' WHERE name = 'Goat Meat Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/chicken_pepper_soup.jpg' WHERE name = 'Chicken Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/abacha.jpg' WHERE name = 'Abacha';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/okpa.jpg' WHERE name = 'Okpa';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/native_jollof_rice.jpg' WHERE name = 'Native Jollof Rice';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/yam_balls.jpg' WHERE name = 'Yam Balls';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/danbu_nama.jpg' WHERE name = 'Dambun Nama';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/mushroom_soup.jpg' WHERE name = 'Mushroom Sauce';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/tuwon_dawa_sauce.jpg' WHERE name = 'Tuwon Dawa Sauce';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/waina.jpg' WHERE name = 'Waina';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/zogale.jpg' WHERE name = 'Zogale';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/okra_soup.jpg' WHERE name = 'Pounded Yam and Vegetable Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/okra_soup.jpg' WHERE name = 'Semovita and Okra Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/efo_riro_semo.jpg' WHERE name = 'Eba';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/ogbono_soup.jpg' WHERE name = 'Fufu and Ogbono Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/ogbono_soup.jpg' WHERE name = 'Eba and Ogbono';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/miyan_kuka.jpg' WHERE name = 'Tuwo Masara and Miyan Kuka';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/lafun.jpg' WHERE name = 'Lafun';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/okra_soup.jpg' WHERE name = 'Tuwo Dawa and Okra Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/efo_riro_semo.jpg' WHERE name = 'Pounded Yam and Efo Riro';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/bitterleaf_soup.jpg' WHERE name = 'Tuwo Shinkafa and Bitterleaf Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/banga_soup.jpg' WHERE name = 'Wheat Flour Swallow and Banga Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/egusi_soup.jpg' WHERE name = 'Tuwo Dawa and Alale Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/lafun.jpg' WHERE name = 'Lafun and Afang Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/nsala_soup.jpg' WHERE name = 'Eba and Nsala Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/abula_amala_ewedu.jpg' WHERE name = 'Amala and Ewedu';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/tuwo_masara_and_miyan_gyada.jpg' WHERE name = 'Tuwo Masara and Miyan Gyada';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/oha_soup.jpg' WHERE name = 'Fufu and Oha Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/groundnut_soup.jpg' WHERE name = 'Eba and Groundnut Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/tuwo_shinkafa_miyan_taushe.jpg' WHERE name = 'Tuwo Shinkafa and Miyan Taushe';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/akara_pap.jpg' WHERE name = 'Akara';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/bread_egg.jpg' WHERE name = 'Bread and Fried Egg';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/indomie.jpg' WHERE name = 'Indomie';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/yam_and_egg_sauce.jpg' WHERE name = 'Yam and Egg Sauce';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/akara_and_bread.jpg' WHERE name = 'Akara and Bread';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/bread_tea.jpg' WHERE name = 'Tea and Bread';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/akara_custard.jpg' WHERE name = 'Custard and Akara';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/pap_(ogi).jpg' WHERE name = 'Pap (Ogi)';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/masa.jpg' WHERE name = 'Masa';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/koko_and_koose.jpg' WHERE name = 'Koko and Koose';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/agege_bread.jpg' WHERE name = 'Alkubus';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/suya.jpg' WHERE name = 'Suya';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/asun.jpg' WHERE name = 'Asun';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/meat_pie.jpg' WHERE name = 'Meat Pie';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/puff_puff.jpg' WHERE name = 'Puff Puff';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/chin_chin.jpg' WHERE name = 'Chin Chin';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/bole.jpg' WHERE name = 'Boli';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/peppered_snail.jpg' WHERE name = 'Peppered Snails';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/scotch_eggs.jpg' WHERE name = 'Scotch Egg';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/egg_roll.jpg' WHERE name = 'Egg Roll';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/nkwobi.jpg' WHERE name = 'Nkwobi';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/isi_ewu.jpg' WHERE name = 'Isi Ewu';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/ugba.jpg' WHERE name = 'Ugba';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/kilishi.jpg' WHERE name = 'Kilishi';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/kuli_kuli.jpg' WHERE name = 'Kuli Kuli';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/balangu.jpg' WHERE name = 'Balangu';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/awara.jpg' WHERE name = 'Awara';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/gizdodo.jpg' WHERE name = 'Gizdodo';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fish_roll.jpg' WHERE name = 'Fish Roll';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/samosa.jpg' WHERE name = 'Samosa';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/buns.jpg' WHERE name = 'Buns';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/gizzard.jpg' WHERE name = 'Gizzard';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/roasted_corn.jpg' WHERE name = 'Roasted Corn';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/boiled_corn.jpg' WHERE name = 'Boiled Corn';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/plantain_chip.jpg' WHERE name = 'Plantain Chips';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/coconut_candy.jpg' WHERE name = 'Coconut Candy';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/groundnut_cake.jpg' WHERE name = 'Groundnut Cake';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/dankwa.jpg' WHERE name = 'Dankwa';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fried_plantain.jpg' WHERE name = 'Fried Plantain (Dodo)';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fried_yam.jpg' WHERE name = 'Fried Yam';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fried_titus_fish.jpg' WHERE name = 'Fried Titus Fish';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/nigerian_salad.jpg' WHERE name = 'Nigerian Salad';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/nigerian_coleslaw.jpg' WHERE name = 'Nigerian Coleslaw';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/boiled_plantain.jpg' WHERE name = 'Boiled Plantain';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/steamed_vegetables.jpg' WHERE name = 'Steamed Vegetables';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fried_chicken.jpg' WHERE name = 'Fried Chicken';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fried_fish.jpg' WHERE name = 'Fried Fish';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/gizzard_sauce.jpg' WHERE name = 'Gizzard Sauce';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/puff_puff_with_honey.jpg' WHERE name = 'Puff Puff with Honey';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/coconut_rice_pudding.jpg' WHERE name = 'Coconut Rice Pudding';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fruit_salad.jpg' WHERE name = 'Fruit Salad';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/peppermint_candy.jpg' WHERE name = 'Peppermint Candy';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/doughnuts.jpg' WHERE name = 'Doughnuts';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/queen_cakes.jpg' WHERE name = 'Queen Cakes';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/pepper_rice.jpg' WHERE name = 'Pepper Rice';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/coconut_jollof_rice.jpg' WHERE name = 'Coconut Jollof Rice';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/yaji_fish.jpg' WHERE name = 'Yaji Fish';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fresh_fish_pepper_soup.jpg' WHERE name = 'Fresh Fish Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/dry_fish_pepper_soup.jpg' WHERE name = 'Dry Fish Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/bushmeat_pepper_soup.jpg' WHERE name = 'Bushmeat Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/catfish_stew.jpg' WHERE name = 'Catfish Stew';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/goat_meat_stew.jpg' WHERE name = 'Goat Meat Stew';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/turkey_pepper_soup.jpg' WHERE name = 'Turkey Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/snail_pepper_soup.jpg' WHERE name = 'Snail Pepper Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/assorted_meat_stew.jpg' WHERE name = 'Assorted Meat Stew';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/white_soup.jpg' WHERE name = 'White Soup';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/yam_and_palm_oil.jpg' WHERE name = 'Yam and Palm Oil';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/akara_and_bread.jpg' WHERE name = 'Bread and Akara';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/agege_bread.jpg' WHERE name = 'Agege Bread';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/plantain_chip.jpg' WHERE name = 'Yaji Chips';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/roasted_groundnut.jpg' WHERE name = 'Roasted Groundnut';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/coconut_flakes.jpg' WHERE name = 'Coconut Flakes';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/sweet_potato_fries.jpg' WHERE name = 'Sweet Potato Fries';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/plantain_egg_sauce.jpg' WHERE name = 'Spicy Fried Potatoes';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/fruit_salad.jpg' WHERE name = 'Zobo Sorbet';
UPDATE meals SET image_url = 'https://res.cloudinary.com/doy5lkpqj/image/upload/naija-eats/kunun_aya_pudding.jpg' WHERE name = 'Kunun Aya Pudding';
